spring.application.name=event-onboarding
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
onboarding.events.exchange=event-onboarding.domain-events
onboarding.events.credit-scoring.routing-key=onboarding.credit-scoring.calculated
onboarding.events.credit-scoring.queue=event-onboarding.credit-scoring-calculated
